spring:
  application:
    name: ecommerce_spring
  datasource:
    url: jdbc:mysql://localhost:3306/store_api
    username: root
    password: admin
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    refreshTokenExpiration: 604800 # 7 days
    accessTokenExpiration: 7200 # 15 mins
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
